// EL REFLEJO DEL TRABAJO EN LA PLANILLA.
//
// El trabajo aprobado es el dueño del dato: cada pago y cada factura suyos se dibujan en el
// Calendario como un renglón `autoGenerated` que apunta al original (sourceJobId + sourceRefId).
//
// Por eso BORRAR ese renglón desde la planilla no puede borrar el reflejo: el trabajo lo vuelve a
// generar y reaparece solo. Hay que borrar el ORIGINAL. Es la contracara de cargar desde la
// planilla — pedido de Nicolas (2026-08-29): "si borro el movimiento también borro la cobranza".

export type MirrorSource = {
  sourceJobId?: number;
  sourceRefId?: number;
  autoGenerated?: boolean;
  preset?: string;
};

/** true si este renglón del calendario es el reflejo de algo que vive en un trabajo aprobado. */
export function esReflejoDeTrabajo(item: MirrorSource | undefined | null): boolean {
  return !!item && !!item.autoGenerated && !!item.sourceJobId && !!item.sourceRefId;
}

/**
 * Saca del trabajo el pago (o la factura) que ese reflejo estaba mostrando.
 * Devuelve la lista de trabajos igual si el reflejo no apunta a nada que exista.
 */
export function borrarOrigenDelReflejo<
  J extends { id?: number; payments?: Array<{ id: number }>; invoices?: Array<{ id: number }> }
>(jobs: J[], item: MirrorSource): J[] {
  if (!esReflejoDeTrabajo(item)) return jobs;
  const esCobranza = item.preset === "cobranza";
  return jobs.map((j) =>
    j.id !== item.sourceJobId
      ? j
      : {
          ...j,
          payments: esCobranza ? (j.payments || []).filter((p) => p.id !== item.sourceRefId) : j.payments,
          invoices: !esCobranza ? (j.invoices || []).filter((i) => i.id !== item.sourceRefId) : j.invoices,
        }
  );
}


/**
 * Cambia el pago del trabajo que ese reflejo esta mostrando.
 *
 * Solo COBRANZAS: una factura necesita subtotal e IVA, y el formulario del calendario no los pide.
 * Editar una factura desde la planilla seria inventarle esos numeros, asi que se sigue editando en
 * Trabajos aprobados. Devuelve null si no se puede aplicar (el que llama avisa donde se edita).
 */
export function editarOrigenDelReflejo<
  J extends { id?: number; payments?: Array<{ id: number; amount: number; paymentDate: string; administration?: "blanco" | "negro" }> }
>(
  jobs: J[],
  item: MirrorSource,
  patch: { amount?: number; date?: string; administration?: "blanco" | "negro" }
): J[] | null {
  if (!esReflejoDeTrabajo(item)) return null;
  if (item.preset !== "cobranza") return null;
  const job = jobs.find((j) => j.id === item.sourceJobId);
  if (!job || !(job.payments || []).some((p) => p.id === item.sourceRefId)) return null;
  return jobs.map((j) =>
    j.id !== item.sourceJobId
      ? j
      : {
          ...j,
          payments: (j.payments || []).map((p) =>
            p.id !== item.sourceRefId
              ? p
              : {
                  ...p,
                  ...(patch.amount !== undefined ? { amount: Number(patch.amount) || 0 } : {}),
                  ...(patch.date ? { paymentDate: patch.date } : {}),
                  ...(patch.administration ? { administration: patch.administration } : {}),
                }
          ),
        }
  );
}
