import { esReflejoDeTrabajo, borrarOrigenDelReflejo, editarOrigenDelReflejo } from "./jobMirror";

const job = () => ({
  id: 7,
  payments: [{ id: 1, amount: 100 }, { id: 2, amount: 200 }],
  invoices: [{ id: 10, total: 500 }],
});
const otro = () => ({ id: 9, payments: [{ id: 1, amount: 999 }], invoices: [] });

describe("esReflejoDeTrabajo", () => {
  it("solo lo es si es autogenerado Y apunta a un trabajo y a un original", () => {
    expect(esReflejoDeTrabajo({ autoGenerated: true, sourceJobId: 7, sourceRefId: 1 })).toBe(true);
    expect(esReflejoDeTrabajo({ autoGenerated: true, sourceJobId: 7 })).toBe(false);
    expect(esReflejoDeTrabajo({ sourceJobId: 7, sourceRefId: 1 })).toBe(false);
    expect(esReflejoDeTrabajo(undefined)).toBe(false);
  });
});

describe("borrarOrigenDelReflejo", () => {
  it("borrar la cobranza de la planilla borra el PAGO del trabajo", () => {
    const r = borrarOrigenDelReflejo([job(), otro()], {
      autoGenerated: true, sourceJobId: 7, sourceRefId: 2, preset: "cobranza",
    });
    expect(r[0].payments.map((p) => p.id)).toEqual([1]);
    expect(r[0].invoices).toHaveLength(1);
  });

  it("no toca los pagos de OTRO trabajo aunque compartan el id del pago", () => {
    const r = borrarOrigenDelReflejo([job(), otro()], {
      autoGenerated: true, sourceJobId: 7, sourceRefId: 1, preset: "cobranza",
    });
    expect(r[1].payments.map((p) => p.id)).toEqual([1]);
  });

  it("si el reflejo es de una factura, borra la FACTURA y no los pagos", () => {
    const r = borrarOrigenDelReflejo([job()], {
      autoGenerated: true, sourceJobId: 7, sourceRefId: 10, preset: "factura",
    });
    expect(r[0].invoices).toEqual([]);
    expect(r[0].payments).toHaveLength(2);
  });

  it("un movimiento suelto (no autogenerado) no toca ningún trabajo", () => {
    const antes = [job()];
    expect(borrarOrigenDelReflejo(antes, { sourceJobId: 7, sourceRefId: 1, preset: "cobranza" })).toBe(antes);
  });

  it("un reflejo que apunta a algo que ya no existe deja todo como estaba", () => {
    const r = borrarOrigenDelReflejo([job()], {
      autoGenerated: true, sourceJobId: 7, sourceRefId: 999, preset: "cobranza",
    });
    expect(r[0].payments).toHaveLength(2);
  });
});


describe("editarOrigenDelReflejo", () => {
  const conPagos = () => [{
    id: 7,
    payments: [
      { id: 1, amount: 100, paymentDate: "2026-08-01", administration: "blanco" as const },
      { id: 2, amount: 200, paymentDate: "2026-08-05", administration: "blanco" as const },
    ],
  }];
  const reflejo = { autoGenerated: true, sourceJobId: 7, sourceRefId: 2, preset: "cobranza" };

  it("editar en la planilla cambia el PAGO del trabajo", () => {
    const r = editarOrigenDelReflejo(conPagos(), reflejo, { amount: 250, date: "2026-08-09", administration: "negro" })!;
    const p = r[0].payments.find((x) => x.id === 2)!;
    expect(p.amount).toBe(250);
    expect(p.paymentDate).toBe("2026-08-09");
    expect(p.administration).toBe("negro");
  });

  it("no toca los otros pagos", () => {
    const r = editarOrigenDelReflejo(conPagos(), reflejo, { amount: 250 })!;
    expect(r[0].payments.find((x) => x.id === 1)!.amount).toBe(100);
  });

  it("una factura NO se edita desde la planilla: le faltan subtotal e IVA", () => {
    expect(editarOrigenDelReflejo(conPagos(), { ...reflejo, preset: "factura" }, { amount: 1 })).toBeNull();
  });

  it("un movimiento suelto o un reflejo colgado devuelven null", () => {
    expect(editarOrigenDelReflejo(conPagos(), { sourceJobId: 7, sourceRefId: 2, preset: "cobranza" }, {})).toBeNull();
    expect(editarOrigenDelReflejo(conPagos(), { ...reflejo, sourceRefId: 999 }, {})).toBeNull();
  });
});
