import { esReflejoDeTrabajo, borrarOrigenDelReflejo } from "./jobMirror";

const job = () => ({
  id: 7,
  payments: [{ id: 1, amount: 100 }, { id: 2, amount: 200 }],
  invoices: [{ id: 10, total: 500 }],
});
const otro = () => ({ id: 9, payments: [{ id: 1, amount: 999 }], invoices: [] });

describe("esReflejoDeTrabajo", () => {
  it("solo lo es si es autogenerado Y apunta a un trabajo y a un original", () => {
    expect(esReflejoDeTrabajo({ autoGenerated: true, sourceJobId: 7, sourceRefId: 1 })).toBe(true);
    expect(esReflejoDeTrabajo({ autoGenerated: true, sourceJobId: 7 })).toBe(false);
    expect(esReflejoDeTrabajo({ sourceJobId: 7, sourceRefId: 1 })).toBe(false);
    expect(esReflejoDeTrabajo(undefined)).toBe(false);
  });
});

describe("borrarOrigenDelReflejo", () => {
  it("borrar la cobranza de la planilla borra el PAGO del trabajo", () => {
    const r = borrarOrigenDelReflejo([job(), otro()], {
      autoGenerated: true, sourceJobId: 7, sourceRefId: 2, preset: "cobranza",
    });
    expect(r[0].payments.map((p) => p.id)).toEqual([1]);
    expect(r[0].invoices).toHaveLength(1);
  });

  it("no toca los pagos de OTRO trabajo aunque compartan el id del pago", () => {
    const r = borrarOrigenDelReflejo([job(), otro()], {
      autoGenerated: true, sourceJobId: 7, sourceRefId: 1, preset: "cobranza",
    });
    expect(r[1].payments.map((p) => p.id)).toEqual([1]);
  });

  it("si el reflejo es de una factura, borra la FACTURA y no los pagos", () => {
    const r = borrarOrigenDelReflejo([job()], {
      autoGenerated: true, sourceJobId: 7, sourceRefId: 10, preset: "factura",
    });
    expect(r[0].invoices).toEqual([]);
    expect(r[0].payments).toHaveLength(2);
  });

  it("un movimiento suelto (no autogenerado) no toca ningún trabajo", () => {
    const antes = [job()];
    expect(borrarOrigenDelReflejo(antes, { sourceJobId: 7, sourceRefId: 1, preset: "cobranza" })).toBe(antes);
  });

  it("un reflejo que apunta a algo que ya no existe deja todo como estaba", () => {
    const r = borrarOrigenDelReflejo([job()], {
      autoGenerated: true, sourceJobId: 7, sourceRefId: 999, preset: "cobranza",
    });
    expect(r[0].payments).toHaveLength(2);
  });
});
