// EL REFLEJO DEL TRABAJO EN LA PLANILLA.
//
// El trabajo aprobado es el dueño del dato: cada pago y cada factura suyos se dibujan en el
// Calendario como un renglón `autoGenerated` que apunta al original (sourceJobId + sourceRefId).
//
// Por eso BORRAR ese renglón desde la planilla no puede borrar el reflejo: el trabajo lo vuelve a
// generar y reaparece solo. Hay que borrar el ORIGINAL. Es la contracara de cargar desde la
// planilla — pedido de Nicolas (2026-08-29): "si borro el movimiento también borro la cobranza".

export type MirrorSource = {
  sourceJobId?: number;
  sourceRefId?: number;
  autoGenerated?: boolean;
  preset?: string;
};

/** true si este renglón del calendario es el reflejo de algo que vive en un trabajo aprobado. */
export function esReflejoDeTrabajo(item: MirrorSource | undefined | null): boolean {
  return !!item && !!item.autoGenerated && !!item.sourceJobId && !!item.sourceRefId;
}

/**
 * Saca del trabajo el pago (o la factura) que ese reflejo estaba mostrando.
 * Devuelve la lista de trabajos igual si el reflejo no apunta a nada que exista.
 */
export function borrarOrigenDelReflejo<
  J extends { id?: number; payments?: Array<{ id: number }>; invoices?: Array<{ id: number }> }
>(jobs: J[], item: MirrorSource): J[] {
  if (!esReflejoDeTrabajo(item)) return jobs;
  const esCobranza = item.preset === "cobranza";
  return jobs.map((j) =>
    j.id !== item.sourceJobId
      ? j
      : {
          ...j,
          payments: esCobranza ? (j.payments || []).filter((p) => p.id !== item.sourceRefId) : j.payments,
          invoices: !esCobranza ? (j.invoices || []).filter((i) => i.id !== item.sourceRefId) : j.invoices,
        }
  );
}
