import { plataDelSistema, type FuentesDePlata } from "./plataDelSistema";
import { armarCuentas, idCajaPersona, idCuentaBanco, idCuentaEfectivo, movimientosPorCuenta, saldosDeCuentas } from "./cuentas";

const vacio = (): FuentesDePlata => ({
  jobs: [],
  costEntries: [],
  financialItems: [],
  haberes: [],
  pettyCashFunds: [],
  pettyCashExpenses: [],
  internalTransfers: [],
  cashHoldings: [],
  personLedgerEntries: [],
  capitalEntries: [],
  ivaVepPayments: [],
});
const cuentas = armarCuentas({
  companies: ["BGA"],
  guardadas: [],
  fechaCorte: "2026-08-29",
  bancosExtracto: [{ company: "BGA", bank: "Santander", currency: "ARS", balance: 1000 }],
  efectivoApertura: [
    { company: "BGA", color: "blanco", moneda: "ARS", saldo: 500 },
    { company: "BGA", color: "negro", moneda: "ARS", saldo: 500 },
  ],
  personas: [],
});
const SANT = idCuentaBanco("BGA", "Santander", "ARS");
const EF_B = idCuentaEfectivo("BGA", "blanco", "ARS");
const EF_N = idCuentaEfectivo("BGA", "negro", "ARS");
const saldos = (f: FuentesDePlata) => {
  const s = saldosDeCuentas(cuentas, movimientosPorCuenta(plataDelSistema(f), cuentas));
  return (id: string) => s.find((c) => c.id === id)?.saldo ?? 0;
};

describe("plataDelSistema -> saldos por cuenta", () => {
  it("cobro por transferencia entra al banco; en efectivo negro, al efectivo negro", () => {
    const f = vacio();
    f.jobs = [{ company: "BGA", budgetNumber: "1", client: "C", payments: [
      { id: 1, paymentDate: "2026-09-10", amount: 300, transactionType: "transferencia", administration: "blanco" },
      { id: 2, paymentDate: "2026-09-10", amount: 100, transactionType: "efectivo", administration: "negro" },
    ] }];
    const s = saldos(f);
    expect(s(SANT)).toBe(1300);
    expect(s(EF_N)).toBe(600);
  });

  it("un gasto sale de la cuenta elegida a mano; uno importado del extracto no cuenta", () => {
    const f = vacio();
    f.costEntries = [
      { id: 1, company: "BGA", date: "2026-09-10", amount: 200, administration: "blanco", source: "manual", paymentMethod: "efectivo", description: "x", cuentaId: SANT },
      { id: 2, company: "BGA", date: "2026-09-10", amount: 999, administration: "blanco", source: "extracto", description: "y" },
    ];
    expect(saldos(f)(SANT)).toBe(800);
  });

  it("sueldo blanco sale del banco y el negro del efectivo negro", () => {
    const f = vacio();
    f.haberes = [
      { id: "payroll-white-1-2026-09", company: "BGA", date: "2026-10-06", amount: 400, title: "A", administration: "blanco" },
      { id: "payroll-black-1-2026-09", company: "BGA", date: "2026-10-06", amount: 100, title: "A", administration: "negro" },
    ];
    const s = saldos(f);
    expect(s(SANT)).toBe(600);
    expect(s(EF_N)).toBe(400);
  });

  it("caja chica: asignar pasa del efectivo a la caja de la persona, el gasto sale de su caja, lo que sobra vuelve al cerrar", () => {
    const f = vacio();
    f.pettyCashFunds = [{ id: 9, company: "BGA", responsible: "Gustavo", assignedAmount: 300, assignedBlack: 300, deliveredDate: "2026-09-01", closed: true, closedDate: "2026-09-30" }];
    f.pettyCashExpenses = [{ id: 1, company: "BGA", fundId: 9, date: "2026-09-10", amount: 120, administration: "negro", description: "ferretería" }];
    const s = saldos(f);
    expect(s(EF_N)).toBe(500 - 300 + 180);
    expect(s(idCajaPersona("BGA", "Gustavo", "negro"))).toBe(0);
  });

  it("pase de efectivo NEGRO al banco: sale del efectivo negro y entra al banco", () => {
    const f = vacio();
    f.internalTransfers = [{ id: 1, company: "BGA", date: "2026-09-10", direction: "efectivo_a_banco", currency: "ARS", color: "negro", amount: 200, bank: "Santander", description: "" }];
    const s = saldos(f);
    expect(s(EF_N)).toBe(300);
    expect(s(SANT)).toBe(1200);
  });

  it("lo pendiente de la planilla y lo generado por los trabajos no es plata movida", () => {
    const f = vacio();
    f.financialItems = [
      { id: 1, company: "BGA", date: "2026-09-10", type: "pago", status: "pendiente", amount: 50, title: "a" },
      { id: 2, company: "BGA", date: "2026-09-10", type: "cobranza", status: "realizado", amount: 50, title: "b", autoGenerated: true },
      { id: 3, company: "BGA", date: "2026-09-10", type: "pago", status: "realizado", amount: 70, title: "c", administration: "blanco" },
    ];
    expect(plataDelSistema(f).map((p) => p.refId)).toEqual(["planilla-3"]);
    expect(saldos(f)(SANT)).toBe(930);
  });

  it("aporte recibido entra, VEP sale del banco, reintegro sale del efectivo", () => {
    const f = vacio();
    f.capitalEntries = [{ id: 1, company: "BGA", date: "2026-09-10", origin: "Gustavo", direction: "recibido", color: "blanco", amount: 100 }];
    f.ivaVepPayments = [{ id: 1, company: "BGA", date: "2026-09-12", amount: 300, period: "09/2026" }];
    f.personLedgerEntries = [{ id: 1, company: "BGA", person: "Nico", date: "2026-09-12", kind: "haber", amount: 50, color: "blanco", description: "" }];
    const s = saldos(f);
    expect(s(SANT)).toBe(1000 + 100 - 300);
    expect(s(EF_B)).toBe(450);
  });

  it("un fondo de caja chica SIN responsable no toca el banco: va a una caja 'Sin responsable'", () => {
    const f = vacio();
    f.pettyCashFunds = [{ id: 1, company: "BGA", responsible: "", assignedAmount: 100, deliveredDate: "2026-09-01", closed: false, closedDate: "" }];
    const s = saldos(f);
    expect(s(SANT)).toBe(1000);
    expect(s(EF_B)).toBe(400);
    expect(s(idCajaPersona("BGA", "Sin responsable", "blanco"))).toBe(100);
  });
});

describe("caja chica: de donde sale y a donde vuelve", () => {
  const vacio2 = (): FuentesDePlata => ({ jobs: [], costEntries: [], financialItems: [], haberes: [], pettyCashFunds: [], pettyCashExpenses: [], internalTransfers: [], cashHoldings: [], personLedgerEntries: [], capitalEntries: [], ivaVepPayments: [] });
  const cs = armarCuentas({ companies: ["BGA"], guardadas: [], fechaCorte: "2026-08-29", bancosExtracto: [{ company: "BGA", bank: "Santander", currency: "ARS", balance: 1000 }], efectivoApertura: [{ company: "BGA", color: "blanco", moneda: "ARS", saldo: 500 }], personas: [] });
  const banco = idCuentaBanco("BGA", "Santander", "ARS");
  const efB = idCuentaEfectivo("BGA", "blanco", "ARS");
  const saldoDe = (f: FuentesDePlata, id: string) =>
    saldosDeCuentas(cs, movimientosPorCuenta(plataDelSistema(f), cs)).find((c) => c.id === id)?.saldo ?? 0;
  const fondo = (over: any) => ({ id: 1, company: "BGA", responsible: "Gustavo", assignedAmount: 100, assignedWhite: 100, deliveredDate: "2026-09-01", closed: true, closedDate: "2026-09-30", ...over });

  it("el fondo sale de la cuenta elegida y lo que sobra vuelve a esa MISMA cuenta", () => {
    const f = vacio2();
    f.pettyCashFunds = [fondo({ cuentaId: banco })];
    f.pettyCashExpenses = [{ id: 1, company: "BGA", fundId: 1, date: "2026-09-10", amount: 30, administration: "blanco", description: "" }];
    expect(saldoDe(f, banco)).toBe(1000 - 100 + 70);
    expect(saldoDe(f, efB)).toBe(500);
  });
  it("si se eligio otra cuenta para la devolucion, vuelve ahi", () => {
    const f = vacio2();
    f.pettyCashFunds = [fondo({ cuentaId: banco, cuentaDevolucionId: efB })];
    expect(saldoDe(f, banco)).toBe(900);
    expect(saldoDe(f, efB)).toBe(600);
  });
});
