// TODA LA PLATA QUE SE MUEVE EN EL SISTEMA, normalizada para las cuentas (ver domain/cuentas.ts).
// Una funcion por solapa; la de abajo las junta. Cada movimiento puede traer la cuenta elegida a mano
// (`cuentaId`, y en los pases `cuentaDestinoId`); si no la trae, cuentas.ts usa la cuenta por defecto.
//
// Lo que NO es plata y por eso no esta aca: facturas (registro), ordenes de compra (sugerencia),
// previsiones (pagos programados, seguros) y los movimientos del extracto (el banco solo controla).
import type { PlataMovida, Moneda, Color } from "./cuentas";

const color = (v?: string): Color => (v === "negro" ? "negro" : "blanco");
const moneda = (v?: string): Moneda => (v === "USD" ? "USD" : "ARS");
const cuenta = (x: any) => (x && typeof x.cuentaId === "string" && x.cuentaId ? x.cuentaId : undefined);

export type FuentesDePlata = {
  jobs: Array<{
    company: string;
    budgetNumber: string;
    client: string;
    payments: Array<{ id: number; paymentDate: string; amount: number; transactionType?: string; administration?: string; currency?: string; cuentaId?: string }>;
    commissionPayments?: Array<{ id: number; paymentDate: string; amount: number; administration?: string; cuentaId?: string }>;
  }>;
  costEntries: Array<{ id: number; company: string; date: string; amount: number; administration: string; source: string; paymentMethod?: string; description: string; supplier?: string; cuentaId?: string }>;
  // Movimientos cargados a mano en la planilla / Facturacion (NO los generados por los trabajos).
  financialItems: Array<{ id: number; company: string; date: string; type: string; status: string; amount: number; title: string; administration?: string; autoGenerated?: boolean; cuentaId?: string }>;
  // Sueldos de la planilla (los automaticos de Personal: ids "payroll-white/black-...").
  haberes: Array<{ id: string; company: string; date: string; amount: number; title: string; administration?: string; cuentaId?: string }>;
  pettyCashFunds: Array<{ id: number; company: string; responsible: string; assignedAmount: number; assignedWhite?: number; assignedBlack?: number; deliveredDate: string; closed: boolean; closedDate: string; cuentaId?: string; cuentaDevolucionId?: string }>;
  pettyCashExpenses: Array<{ id: number; company: string; fundId: number | null; date: string; amount: number; administration: string; description: string }>;
  internalTransfers: Array<{ id: number; company: string; date: string; direction: string; currency: string; color: string; amount: number; bank: string; description: string; cuentaId?: string; cuentaDestinoId?: string }>;
  cashHoldings: Array<{ id: number; company: string; date: string; currency: string; color: string; kind: string; amount: number; description: string; cuentaId?: string }>;
  personLedgerEntries: Array<{ id: number; company: string; person: string; date: string; kind: string; amount: number; color: string; paymentMethod?: string; description: string; cuentaId?: string }>;
  capitalEntries: Array<{ id: number; company: string; date: string; origin: string; direction: string; color: string; amount: number; cuentaId?: string }>;
  ivaVepPayments: Array<{ id: number; company: string; date: string; amount: number; period: string; cuentaId?: string }>;
};

export function plataDelSistema(f: FuentesDePlata): PlataMovida[] {
  const out: PlataMovida[] = [];

  // COBROS de trabajos (Trabajos aprobados) y COMISIONES pagadas.
  f.jobs.forEach((j) => {
    (j.payments || []).forEach((p) =>
      out.push({
        refId: `cobro-${p.id}`,
        origen: "Cobro de trabajo",
        detalle: `${j.budgetNumber} · ${j.client}`,
        company: j.company,
        date: p.paymentDate,
        amount: Number(p.amount || 0),
        sentido: "entra",
        moneda: moneda(p.currency),
        color: color(p.administration),
        metodo: p.transactionType,
        cuentaId: cuenta(p),
      })
    );
    (j.commissionPayments || []).forEach((c) =>
      out.push({
        refId: `comision-${c.id}`,
        origen: "Comisión",
        detalle: `${j.budgetNumber} · ${j.client}`,
        company: j.company,
        date: c.paymentDate,
        amount: Number(c.amount || 0),
        sentido: "sale",
        moneda: "ARS",
        color: color(c.administration),
        cuentaId: cuenta(c),
      })
    );
  });

  // GASTOS (Pago a proveedores / Costos). Los importados del extracto no: el banco solo controla.
  f.costEntries
    .filter((c) => c.source !== "extracto")
    .forEach((c) =>
      out.push({
        refId: `gasto-${c.id}`,
        origen: "Gasto",
        detalle: [c.supplier, c.description].filter(Boolean).join(" · "),
        company: c.company,
        date: c.date,
        amount: Number(c.amount || 0),
        sentido: "sale",
        moneda: "ARS",
        color: color(c.administration),
        metodo: c.paymentMethod,
        cuentaId: cuenta(c),
      })
    );

  // COBROS y PAGOS cargados a mano en la planilla (los realizados; los pendientes son prevision).
  f.financialItems
    .filter((i) => !i.autoGenerated && i.status === "realizado" && (i.type === "cobranza" || i.type === "pago"))
    .forEach((i) =>
      out.push({
        refId: `planilla-${i.id}`,
        origen: i.type === "cobranza" ? "Cobro cargado en la planilla" : "Pago cargado en la planilla",
        detalle: i.title,
        company: i.company,
        date: i.date,
        amount: Number(i.amount || 0),
        sentido: i.type === "cobranza" ? "entra" : "sale",
        moneda: "ARS",
        color: color(i.administration),
        cuentaId: cuenta(i),
      })
    );

  // SUELDOS (Personal -> Haberes): blanco por banco, negro en efectivo, salvo cuenta elegida.
  f.haberes.forEach((h) =>
    out.push({
      refId: h.id,
      origen: "Sueldo",
      detalle: h.title,
      company: h.company,
      date: h.date,
      amount: Number(h.amount || 0),
      sentido: "sale",
      moneda: "ARS",
      color: color(h.administration),
      metodo: color(h.administration) === "negro" ? "efectivo" : "transferencia",
      cuentaId: cuenta(h),
    })
  );

  // CAJA CHICA: asignar el fondo es un PASE de la caja de la empresa a la caja de la persona (por color);
  // el gasto sale de la caja de la persona; al cerrar el fondo, lo que sobra vuelve.
  f.pettyCashFunds.forEach((fund) => {
    const blanco = Number(fund.assignedWhite || 0);
    const negro = Number(fund.assignedBlack || 0);
    const partes: Array<[Color, number]> =
      blanco || negro ? [["blanco", blanco], ["negro", negro]] : [["blanco", Number(fund.assignedAmount || 0)]];
    partes.forEach(([c, monto]) => {
      if (!(monto > 0)) return;
      out.push({
        refId: `fondo-${fund.id}-${c}`,
        origen: "Caja chica (asignación)",
        detalle: fund.responsible,
        company: fund.company,
        date: fund.deliveredDate,
        amount: monto,
        sentido: "pase",
        moneda: "ARS",
        color: c,
        desde: "efectivo",
        cuentaId: cuenta(fund),
        // Sin responsable cargado la plata igual sale de la caja de la empresa: va a una caja aparte
        // para que se vea (si no, el pase no tendria destino).
        personaDestino: fund.responsible || "Sin responsable",
      });
      if (fund.closed && fund.closedDate) {
        const gastado = f.pettyCashExpenses
          .filter((e) => e.fundId === fund.id && color(e.administration) === c)
          .reduce((a, e) => a + Number(e.amount || 0), 0);
        const sobra = monto - gastado;
        if (sobra > 0)
          out.push({
            refId: `fondo-cierre-${fund.id}-${c}`,
            origen: "Caja chica (devolución al cerrar)",
            detalle: fund.responsible,
            company: fund.company,
            date: fund.closedDate,
            amount: sobra,
            sentido: "pase",
            moneda: "ARS",
            color: c,
            persona: fund.responsible || "Sin responsable",
            // Vuelve a la cuenta elegida; si no se eligio, a la misma de donde salio el fondo.
            cuentaDestinoId: fund.cuentaDevolucionId || fund.cuentaId,
            hacia: "efectivo",
          });
      }
    });
  });
  const responsable = new Map(f.pettyCashFunds.map((x) => [x.id, x.responsible || "Sin responsable"]));
  f.pettyCashExpenses.forEach((e) =>
    out.push({
      refId: `gasto-caja-${e.id}`,
      origen: "Gasto de caja chica",
      detalle: e.description,
      company: e.company,
      date: e.date,
      amount: Number(e.amount || 0),
      sentido: "sale",
      moneda: "ARS",
      color: color(e.administration),
      metodo: "efectivo",
      persona: (e.fundId != null && responsable.get(e.fundId)) || undefined,
    })
  );

  // PASES efectivo <-> banco (Movimientos internos).
  f.internalTransfers.forEach((t) => {
    const deEfectivo = t.direction === "efectivo_a_banco";
    out.push({
      refId: `pase-${t.id}`,
      origen: "Pase efectivo ↔ banco",
      detalle: t.description || t.bank,
      company: t.company,
      date: t.date,
      amount: Number(t.amount || 0),
      sentido: "pase",
      moneda: moneda(t.currency),
      color: color(t.color),
      desde: deEfectivo ? "efectivo" : "banco",
      hacia: deEfectivo ? "banco" : "efectivo",
      cuentaId: cuenta(t),
      cuentaDestinoId: t.cuentaDestinoId,
    });
  });

  // EFECTIVO GUARDADO a mano (caja de seguridad, plata en mano).
  f.cashHoldings.forEach((h) =>
    out.push({
      refId: `efectivo-${h.id}`,
      origen: "Efectivo (carga a mano)",
      detalle: h.description,
      company: h.company,
      date: h.date,
      amount: Number(h.amount || 0),
      sentido: h.kind === "egreso" ? "sale" : "entra",
      moneda: moneda(h.currency),
      color: color(h.color),
      metodo: "efectivo",
      cuentaId: cuenta(h),
    })
  );

  // REINTEGROS a la gente (cuenta corriente con la gente): el "haber" es plata que sale.
  f.personLedgerEntries
    .filter((p) => p.kind === "haber")
    .forEach((p) =>
      out.push({
        refId: `reintegro-${p.id}`,
        origen: "Reintegro a una persona",
        detalle: p.person,
        company: p.company,
        date: p.date,
        amount: Number(p.amount || 0),
        sentido: "sale",
        moneda: "ARS",
        color: color(p.color),
        metodo: p.paymentMethod || "efectivo",
        cuentaId: cuenta(p),
      })
    );

  // APORTES y PRESTAMOS (Deudas y aportes): recibido entra, devuelto sale.
  f.capitalEntries.forEach((c) =>
    out.push({
      refId: `aporte-${c.id}`,
      origen: c.direction === "devuelto" ? "Devolución de aporte/préstamo" : "Aporte / préstamo recibido",
      detalle: c.origin,
      company: c.company,
      date: c.date,
      amount: Number(c.amount || 0),
      sentido: c.direction === "devuelto" ? "sale" : "entra",
      moneda: "ARS",
      color: color(c.color),
      cuentaId: cuenta(c),
    })
  );

  // VEP de IVA: sale del banco.
  f.ivaVepPayments.forEach((v) =>
    out.push({
      refId: `vep-${v.id}`,
      origen: "VEP IVA",
      detalle: v.period,
      company: v.company,
      date: v.date,
      amount: Number(v.amount || 0),
      sentido: "sale",
      moneda: "ARS",
      color: "blanco",
      metodo: "transferencia",
      cuentaId: cuenta(v),
    })
  );

  return out.filter((p) => p.date && Number(p.amount) > 0);
}
