import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: {
    padding: 18,
    background: "#f8fafc",
    minHeight: "100vh",
    color: "#0f172a",
    fontFamily: "Arial, sans-serif",
  },
  headerBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    background: "white",
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
  },
  tabsRow: { display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 18 },
  workspaceShell: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    gap: 14,
    alignItems: "start",
  },
  workspaceMain: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  sidebar: {
    position: "sticky",
    top: 20,
    alignSelf: "start",
    minHeight: "calc(100vh - 36px)",
    borderRadius: 24,
    padding: 12,
    background: "linear-gradient(180deg, #0f172a 0%, #1e293b 100%)",
    boxShadow: "0 18px 40px rgba(15,23,42,0.18)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
    overflow: "hidden",
  },
  sidebarTitle: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 1,
    textTransform: "uppercase",
    padding: "6px 8px 2px",
  },
  sidebarTabs: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    paddingRight: 4,
  },
  sidebarFooter: {
    marginTop: "auto",
    display: "grid",
    gap: 10,
    paddingTop: 12,
    borderTop: "1px solid rgba(255,255,255,0.12)",
  },
  assistantDockButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 18,
    border: "1px solid rgba(255,255,255,0.16)",
    background: "rgba(255,255,255,0.08)",
    color: "#ffffff",
    cursor: "pointer",
    fontWeight: 800,
    textAlign: "left",
    boxShadow: "0 8px 18px rgba(15,23,42,0.18)",
  },
  assistantDockIcon: {
    width: 38,
    height: 38,
    borderRadius: 14,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(255,255,255,0.18)",
    fontSize: 18,
    fontWeight: 900,
    flexShrink: 0,
  },
  assistantDockTextWrap: {
    display: "grid",
    gap: 2,
    minWidth: 0,
  },
  assistantDockCaption: {
    fontSize: 11,
    color: "rgba(255,255,255,0.7)",
    fontWeight: 600,
  },
  sidebarSection: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  sidebarSectionTitleWrap: {
    padding: "8px 10px 2px",
  },
  sidebarSectionTitle: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  sidebarSectionHint: {
    marginTop: 2,
    color: "rgba(255,255,255,0.62)",
    fontSize: 11,
  },
  sidebarTab: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(255,255,255,0.04)",
    color: "#e2e8f0",
    borderRadius: 16,
    padding: "10px 12px",
    cursor: "pointer",
    textAlign: "left",
    fontWeight: 600,
  },
  sidebarTabActive: {
    background: "linear-gradient(135deg, #dbeafe 0%, #ffffff 100%)",
    color: "#0f172a",
    borderColor: "#bfdbfe",
    boxShadow: "0 10px 24px rgba(59,130,246,0.18)",
  },
  sidebarTabBadge: {
    width: 34,
    height: 34,
    borderRadius: 12,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(255,255,255,0.12)",
    fontSize: 11,
    fontWeight: 800,
    flexShrink: 0,
  },
  sidebarTabTextWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  sidebarTabCaption: {
    color: "rgba(148,163,184,0.95)",
    fontSize: 11,
    fontWeight: 600,
  },
  pettyCashFundGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: 16,
  },
  pettyCashFundCard: {
    border: "1px solid #d6d3d1",
    borderRadius: 18,
    padding: 16,
    background: "#fffbeb",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  pettyCashFundHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    flexWrap: "wrap",
  },
  pettyCashFundTitle: {
    display: "grid",
    gap: 4,
  },
  pettyCashFundSummary: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 10,
  },
  pettyCashFundMetric: {
    border: "1px solid #e7e5e4",
    borderRadius: 14,
    padding: 12,
    background: "white",
  },
  pettyCashFundState: {
    display: "inline-flex",
    alignItems: "center",
    alignSelf: "flex-start",
    padding: "6px 10px",
    borderRadius: 999,
    background: "#292524",
    color: "#ffffff",
    fontSize: 12,
    fontWeight: 700,
  },
  pettyCashInlineBubble: {
    border: "1px solid #fde68a",
    borderRadius: 16,
    padding: 14,
    background: "#fff7d6",
    display: "grid",
    gap: 12,
  },
  pettyCashExpenseSummary: {
    display: "grid",
    gap: 4,
    cursor: "pointer",
    listStyle: "none",
  },
  pettyCashExpenseSummaryLine: {
    display: "block",
    color: "#1f2937",
    fontSize: 13,
    lineHeight: 1.4,
  },
  inlineForm: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 8,
    alignItems: "end",
  },
  tab: {
    padding: "10px 14px",
    borderRadius: 12,
    border: "1px solid #cbd5e1",
    background: "white",
    cursor: "pointer",
  },
  tabActive: {
    padding: "10px 14px",
    borderRadius: 12,
    border: "1px solid #0f172a",
    background: "#0f172a",
    color: "white",
    cursor: "pointer",
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 12,
    alignItems: "start",
  },
  budgetLayout: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.8fr) minmax(320px, 1fr)",
    gap: 14,
    alignItems: "start",
  },
  budgetMainTop: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    gridColumn: "1",
    gridRow: "1",
  },
  budgetMainBottom: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    gridColumn: "1",
    gridRow: "2",
  },
  budgetAside: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    gridColumn: "2",
    gridRow: "1 / span 2",
  },
  budgetHistorySection: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    gridColumn: "1 / -1",
    gridRow: "3",
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 10,
    alignItems: "start",
  },
  personalStack: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 18,
    alignItems: "start",
    width: "100%",
  },
  personalFichaStack: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 16,
    width: "100%",
  },
  personalAttendancePayrollGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(720px, 3fr) minmax(320px, 1fr)",
    gap: 16,
    width: "100%",
    alignItems: "start",
    overflowX: "auto",
    paddingBottom: 2,
  },
  personalAttendancePane: {
    minWidth: 0,
    width: "100%",
  },
  personalPayrollPane: {
    minWidth: 320,
    width: "100%",
  },
  liquidationColumn: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 10,
  },
  employeeSubsection: {
    marginTop: 14,
    paddingTop: 14,
    borderTop: "1px solid #e2e8f0",
  },
  savedMonthsList: {
    display: "grid",
    gap: 8,
    marginTop: 12,
    justifyItems: "start",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 80,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "48px 24px",
    background: "rgba(15,23,42,0.45)",
    overflowY: "auto",
  },
  employeeSetupModal: {
    width: "min(620px, calc(100vw - 48px))",
    maxHeight: "calc(100vh - 96px)",
    overflowY: "auto",
    borderRadius: 24,
    boxShadow: "0 28px 70px rgba(15,23,42,0.32)",
  },
  column: {
    display: "grid",
    gridTemplateColumns: "repeat(12, minmax(0, 1fr))",
    gap: 14,
    alignItems: "start",
    gridAutoFlow: "dense",
  },
  // Layout master-detalle: contenido principal a ancho flexible + panel lateral sticky.
  // Cuando el aside no se renderiza, la 2da columna ("auto") colapsa y el main ocupa todo.
  masterDetailLayout: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 14,
    alignItems: "start",
  },
  masterDetailMain: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    minWidth: 0,
  },
  masterDetailAside: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    position: "sticky",
    top: 16,
    width: 360,
    maxWidth: "100%",
    alignSelf: "start",
  },
  panel: {
    background: "white",
    borderRadius: 18,
    padding: 14,
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    gridColumn: "span 4",
    minWidth: 0,
  },
  panelHalf: {
    gridColumn: "span 6",
  },
  panelWide: {
    gridColumn: "1 / -1",
  },
  panelFull: {
    gridColumn: "1 / -1",
  },
  nestedPanel: {
    boxShadow: "none",
    border: "1px solid #e2e8f0",
    borderRadius: 14,
  },
  greenPanel: { border: "2px solid #22c55e", background: "#f0fdf4" },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
    flexWrap: "wrap",
  },
  panelTitleToggle: {
    flex: "1 1 auto",
    minWidth: 200,
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 16,
    border: "1px solid #bfdbfe",
    background: "linear-gradient(135deg, #eff6ff 0%, #ffffff 100%)",
    color: "#0f172a",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: 16,
    textAlign: "left",
    boxShadow: "0 8px 20px rgba(148,163,184,0.12)",
  },
  panelCollapseBadge: {
    width: 30,
    height: 30,
    borderRadius: 12,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#0f172a",
    color: "white",
    fontSize: 18,
    fontWeight: 800,
    flexShrink: 0,
  },
  panelHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  panelHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    marginLeft: "auto",
  },
  label: { fontSize: 12, color: "#475569", marginBottom: 6, fontWeight: 600 },
  input: {
    width: "100%",
    padding: "9px 10px",
    borderRadius: 10,
    border: "1px solid #cbd5e1",
    boxSizing: "border-box",
  },
  inputReadOnly: {
    width: "100%",
    padding: "9px 10px",
    borderRadius: 10,
    border: "1px solid #cbd5e1",
    boxSizing: "border-box",
    background: "#f8fafc",
    color: "#475569",
  },
  textarea: {
    width: "100%",
    minHeight: 72,
    padding: "9px 10px",
    borderRadius: 10,
    border: "1px solid #cbd5e1",
    boxSizing: "border-box",
  },
  table: { width: "100%", borderCollapse: "collapse" },
  metric: {
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    padding: 14,
    background: "#f8fafc",
  },
  metricLabel: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  metricValue: {
    fontWeight: 700,
    fontSize: 20,
    color: "#0f172a",
    marginTop: 4,
    lineHeight: 1.2,
  },
  metricGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(230px, 1fr))",
    gap: "2px 24px",
    marginTop: 8,
  },
  rightStrong: {
    textAlign: "right",
    fontWeight: 700,
    marginTop: 10,
  },
  muted: { color: "#475569", fontSize: 13 },
  empty: {
    padding: 16,
    border: "1px dashed #cbd5e1",
    borderRadius: 12,
    color: "#64748b",
    background: "#fff",
  },
  noticeBox: {
    padding: 12,
    borderRadius: 12,
    background: "#eff6ff",
    border: "1px solid #93c5fd",
    color: "#1e3a8a",
    marginBottom: 12,
  },
  nestedCard: {
    border: "1px solid #cbd5e1",
    borderRadius: 16,
    padding: 14,
    background: "#ffffff",
    marginTop: 12,
    boxShadow: "0 10px 24px rgba(15,23,42,0.05)",
  },
  button: {
    padding: "9px 12px",
    borderRadius: 10,
    border: "1px solid #0f172a",
    background: "#0f172a",
    color: "white",
    cursor: "pointer",
  },
  buttonSecondary: { background: "white", color: "#0f172a" },
  buttonDisabled: {
    opacity: 0.55,
    cursor: "not-allowed",
  },
  smallBtn: {
    padding: "6px 10px",
    borderRadius: 8,
    border: "1px solid #cbd5e1",
    background: "white",
    cursor: "pointer",
  },
  uploadActions: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 8,
    marginBottom: 8,
  },
  inlineActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 8,
  },
  buttonLikeLabel: {
    padding: "9px 12px",
    borderRadius: 10,
    border: "1px solid #0f172a",
    background: "#0f172a",
    color: "white",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
  },
  fileName: { marginTop: 8, fontSize: 12, color: "#64748b" },
  companyRibbon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "6px 12px",
    borderRadius: 999,
    fontWeight: 800,
  },
  companyRibbonMini: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    borderRadius: 999,
    fontWeight: 700,
    fontSize: 11,
    marginTop: 6,
  },
  previewCard: {
    border: "1px solid #cbd5e1",
    borderRadius: 16,
    padding: 16,
    background: "linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)",
  },
  previewHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    marginBottom: 16,
  },
  previewLogoRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 10,
  },
  previewLogo: {
    width: 54,
    height: 54,
    objectFit: "contain",
    borderRadius: 10,
    border: "1px solid #e2e8f0",
    background: "white",
    padding: 4,
  },
  previewMeta: { display: "grid", gap: 6, fontSize: 14 },
  previewBlock: {
    borderTop: "1px solid #e2e8f0",
    paddingTop: 12,
    marginTop: 12,
  },
  previewImage: {
    width: "100%",
    maxHeight: 220,
    objectFit: "contain",
    borderRadius: 12,
    marginTop: 10,
  },
  referenceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 12,
    marginTop: 12,
  },
  referenceCard: {
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    padding: 10,
    background: "#fff",
  },
  referenceThumb: {
    width: "100%",
    height: 160,
    objectFit: "cover",
    borderRadius: 10,
    display: "block",
  },
  materialColumns: {
    columnCount: 3,
    columnGap: 18,
    marginTop: 8,
  },
  materialColumnItem: {
    breakInside: "avoid",
    marginBottom: 6,
    lineHeight: 1.4,
  },
  sectionCell: {
    padding: 0,
    background: "transparent",
    borderBottom: "none",
  },
  sectionHeader: {
    padding: "10px 12px",
    borderRadius: 12,
    fontWeight: 800,
    border: "2px solid",
    margin: "8px 0",
  },
  statusPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 10px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
  },
  accessShell: {
    minHeight: "70vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 0 40px",
  },
  accessCard: {
    width: "100%",
    maxWidth: 980,
    display: "grid",
    gridTemplateColumns: "1.1fr 0.9fr",
    gap: 24,
    alignItems: "stretch",
  },
  accessBrand: {
    minHeight: 520,
    borderRadius: 28,
    padding: 34,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    background:
      "radial-gradient(circle at top, rgba(59,130,246,0.22), rgba(255,255,255,0.96) 42%), linear-gradient(145deg, #ffffff, #eff6ff)",
    border: "1px solid #bfdbfe",
    boxShadow: "0 20px 50px rgba(15,23,42,0.08)",
  },
  accessLogo: {
    width: 140,
    maxHeight: 110,
    objectFit: "contain",
    marginBottom: 22,
  },
  accessLogoPlaceholder: {
    width: 112,
    height: 112,
    borderRadius: 26,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 22,
    background: "linear-gradient(145deg, #1d4ed8, #0f172a)",
    color: "white",
    fontSize: 30,
    fontWeight: 800,
    letterSpacing: 1,
    boxShadow: "0 18px 40px rgba(29,78,216,0.28)",
  },
  accessTitle: {
    fontSize: 40,
    fontWeight: 800,
    color: "#0f172a",
    marginBottom: 8,
  },
  accessSubtitle: {
    fontSize: 18,
    fontWeight: 600,
    color: "#1d4ed8",
    marginBottom: 12,
  },
  accessSubcompaniesHint: {
    maxWidth: 420,
    fontSize: 14,
    lineHeight: 1.5,
    color: "#64748b",
  },
  accessFormCard: {
    borderRadius: 28,
    padding: 30,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "0 20px 50px rgba(15,23,42,0.08)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  accessFormTitle: {
    fontSize: 26,
    fontWeight: 800,
    color: "#0f172a",
    marginBottom: 8,
  },
  accessFormText: {
    fontSize: 14,
    lineHeight: 1.5,
    color: "#64748b",
    marginBottom: 18,
  },
  accessInputStack: {
    display: "grid",
    gap: 12,
    marginBottom: 14,
  },
  accessInput: {
    width: "100%",
    padding: "13px 14px",
    borderRadius: 14,
    border: "1px solid #cbd5e1",
    boxSizing: "border-box",
    fontSize: 15,
    background: "#f8fafc",
  },
  accessSubmitBtn: {
    width: "100%",
    padding: "13px 16px",
    borderRadius: 14,
    border: "none",
    background: "linear-gradient(145deg, #0f172a, #1d4ed8)",
    color: "white",
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
    boxShadow: "0 18px 35px rgba(29,78,216,0.22)",
  },
  accessSecondaryBtn: {
    width: "100%",
    marginTop: 10,
    padding: "12px 16px",
    borderRadius: 14,
    border: "1px solid #cbd5e1",
    background: "#f8fafc",
    color: "#0f172a",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
  },
  accessHelpText: {
    marginTop: 12,
    fontSize: 13,
    lineHeight: 1.5,
    color: "#64748b",
  },
  accessFeedback: {
    marginTop: 12,
    padding: "10px 12px",
    borderRadius: 12,
    background: "#eff6ff",
    border: "1px solid #bfdbfe",
    color: "#1e3a8a",
    fontSize: 13,
  },
  collaborationBanner: {
    padding: "12px 14px",
    borderRadius: 14,
    background: "#ecfeff",
    border: "1px solid #a5f3fc",
    color: "#155e75",
    marginBottom: 18,
    display: "grid",
    gap: 6,
  },
  collaborationBannerMeta: {
    fontSize: 13,
    color: "#0f766e",
    lineHeight: 1.45,
  },
  collaborationBannerActions: {
    display: "flex",
    gap: 10,
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
  },
  workspaceToolbar: {
    display: "grid",
    gridTemplateColumns: "minmax(280px, 360px) minmax(0, 1fr)",
    gap: 16,
    alignItems: "end",
    background: "linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)",
    border: "1px solid #dbeafe",
    borderRadius: 18,
    padding: 16,
    boxShadow: "0 12px 30px rgba(15,23,42,0.06)",
  },
  workspaceToolbarBlock: {
    display: "grid",
    gap: 6,
  },
  workspaceToolbarInfo: {
    fontSize: 13,
    lineHeight: 1.5,
    color: "#475569",
    background: "#eff6ff",
    border: "1px solid #bfdbfe",
    borderRadius: 14,
    padding: "10px 12px",
  },
  communicationRail: {
    position: "sticky",
    top: 20,
    alignSelf: "start",
    minHeight: "calc(100vh - 48px)",
    borderRadius: 24,
    padding: 14,
    color: "#ffffff",
    boxShadow: "0 18px 40px rgba(15,23,42,0.18)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
    overflow: "hidden",
  },
  communicationRailTitle: {
    color: "rgba(255,255,255,0.84)",
    fontSize: 18,
    fontWeight: 800,
    letterSpacing: 0.5,
    textTransform: "none",
    padding: "6px 8px 4px",
    textAlign: "center",
  },
  communicationSection: {
    display: "grid",
    gap: 10,
  },
  communicationSectionButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 18,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "rgba(255,255,255,0.08)",
    color: "#ffffff",
    cursor: "pointer",
    fontWeight: 800,
    textAlign: "left",
  },
  communicationContactsList: {
    display: "grid",
    gap: 8,
    paddingRight: 0,
    maxHeight: "calc(100vh - 220px)",
    overflowY: "auto",
    overflowX: "hidden",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
  },
  communicationCard: {
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "rgba(255,255,255,0.94)",
    color: "#0f172a",
    boxShadow: "0 16px 36px rgba(15,23,42,0.2)",
    overflow: "hidden",
  },
  notificationsToggle: {
    position: "fixed",
    right: 24,
    bottom: 92,
    zIndex: 42,
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 16px",
    borderRadius: 16,
    border: "1px solid #0f172a",
    background: "#ffffff",
    color: "#0f172a",
    boxShadow: "0 18px 36px rgba(15,23,42,0.18)",
    cursor: "pointer",
    fontWeight: 700,
  },
  notificationsPanel: {
    position: "fixed",
    right: 24,
    bottom: 150,
    width: 360,
    maxWidth: "calc(100vw - 48px)",
    maxHeight: "calc(100vh - 180px)",
    zIndex: 41,
    borderRadius: 22,
    border: "1px solid #cbd5e1",
    background: "rgba(255,255,255,0.98)",
    boxShadow: "0 22px 48px rgba(15,23,42,0.22)",
    display: "grid",
    overflow: "hidden",
  },
  notificationsList: {
    display: "grid",
    gap: 10,
    maxHeight: "calc(100vh - 280px)",
    overflowY: "auto",
    padding: 16,
  },
  notificationItem: {
    borderRadius: 14,
    padding: "12px 14px",
    border: "1px solid #e2e8f0",
    background: "#ffffff",
    display: "grid",
    gap: 8,
  },
  notificationItemUnread: {
    background: "#eff6ff",
    borderColor: "#93c5fd",
  },
  fileDropZone: {
    display: "grid",
    gap: 8,
    padding: 12,
    borderRadius: 14,
    border: "1px dashed #94a3b8",
    background: "#f8fafc",
    minWidth: 220,
  },
  fileDropZoneActive: {
    borderColor: "#1d4ed8",
    background: "#eff6ff",
  },
  fileDropLabel: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "10px 14px",
    borderRadius: 12,
    background: "#0f172a",
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
  },
  fileDropHint: {
    fontSize: 12,
    color: "#475569",
    lineHeight: 1.4,
  },
  chatLauncherRail: {
    position: "fixed",
    right: 24,
    bottom: 154,
    zIndex: 43,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 10,
  },
  chatContactsPopover: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 18,
    background: "rgba(255,255,255,0.98)",
    border: "1px solid #cbd5e1",
    boxShadow: "0 16px 36px rgba(15,23,42,0.18)",
  },
  chatContactBubble: {
    width: "100%",
    minHeight: 64,
    borderRadius: 16,
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#0f172a",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 12,
    padding: "12px 14px",
    fontWeight: 800,
    cursor: "pointer",
    position: "relative",
    boxShadow: "0 8px 16px rgba(15,23,42,0.08)",
  },
  chatContactBubbleActive: {
    background: "#0f172a",
    color: "#ffffff",
    borderColor: "#0f172a",
  },
  chatContactUnread: {
    position: "absolute",
    top: -6,
    right: -6,
    minWidth: 20,
    height: 20,
    borderRadius: 999,
    padding: "0 5px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#dc2626",
    color: "#ffffff",
    fontSize: 11,
    fontWeight: 800,
    border: "2px solid #ffffff",
  },
  chatContactAvatar: {
    width: 42,
    height: 42,
    borderRadius: 999,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(15,23,42,0.08)",
    fontSize: 13,
    fontWeight: 800,
    flexShrink: 0,
  },
  chatContactLabel: {
    fontSize: 12,
    fontWeight: 700,
    flex: 1,
    minWidth: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    lineHeight: 1.2,
  },
  chatOverlay: {
    position: "fixed",
    right: 96,
    top: 84,
    bottom: 18,
    width: "min(440px, calc(100vw - 180px))",
    zIndex: 52,
    borderRadius: 22,
    border: "1px solid #cbd5e1",
    background: "rgba(255,255,255,0.98)",
    boxShadow: "0 22px 48px rgba(15,23,42,0.24)",
    display: "grid",
    overflow: "hidden",
  },
  assistantOverlay: {
    position: "fixed",
    left: 104,
    bottom: 24,
    width: "min(420px, calc(100vw - 180px))",
    maxHeight: "calc(100vh - 140px)",
    zIndex: 51,
    borderRadius: 22,
    border: "1px solid #cbd5e1",
    background: "rgba(255,255,255,0.98)",
    boxShadow: "0 22px 48px rgba(15,23,42,0.24)",
    display: "grid",
    overflow: "hidden",
  },
  chatMessagesLarge: {
    display: "grid",
    gap: 10,
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    paddingRight: 4,
  },
  chatPanel: {
    display: "grid",
    gap: 14,
  },
  chatMessages: {
    display: "grid",
    gap: 10,
    maxHeight: 340,
    overflowY: "auto",
    paddingRight: 4,
  },
  chatMessage: {
    borderRadius: 14,
    padding: "12px 14px",
    border: "1px solid #e2e8f0",
  },
  chatMessageOwn: {
    background: "#dbeafe",
    borderColor: "#93c5fd",
  },
  chatMessageOther: {
    background: "#f8fafc",
    borderColor: "#cbd5e1",
  },
  chatMessageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
    fontSize: 13,
  },
  chatTimestamp: {
    color: "#64748b",
    fontSize: 12,
  },
  chatComposer: {
    display: "grid",
    gap: 10,
  },
  chatTextarea: {
    width: "100%",
    minHeight: 84,
    padding: "11px 12px",
    borderRadius: 12,
    border: "1px solid #cbd5e1",
    boxSizing: "border-box",
    resize: "vertical",
  },
  chatActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    flexWrap: "wrap",
  },
  chatStatus: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: 600,
  },
  workspaceWidgetToggle: {
    position: "fixed",
    right: 24,
    bottom: 24,
    zIndex: 40,
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    padding: "14px 18px",
    borderRadius: 18,
    border: "1px solid #0f172a",
    background: "#0f172a",
    color: "white",
    boxShadow: "0 18px 36px rgba(15,23,42,0.28)",
    cursor: "pointer",
    fontWeight: 700,
  },
  workspaceWidgetBadge: {
    minWidth: 26,
    height: 26,
    borderRadius: 999,
    padding: "0 8px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#dbeafe",
    color: "#1d4ed8",
    fontSize: 12,
    fontWeight: 800,
  },
  workspaceWidget: {
    position: "fixed",
    right: 24,
    bottom: 86,
    width: 420,
    maxWidth: "calc(100vw - 48px)",
    maxHeight: "calc(100vh - 120px)",
    zIndex: 39,
    borderRadius: 22,
    border: "1px solid #cbd5e1",
    background: "rgba(255,255,255,0.98)",
    boxShadow: "0 22px 48px rgba(15,23,42,0.24)",
    display: "grid",
    overflow: "hidden",
  },
  workspaceWidgetHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    padding: 16,
    borderBottom: "1px solid #e2e8f0",
    background: "linear-gradient(135deg, #eff6ff 0%, #ffffff 100%)",
  },
  workspaceWidgetTitle: {
    fontSize: 18,
    fontWeight: 800,
    color: "#0f172a",
    marginBottom: 4,
  },
  workspaceWidgetTabs: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  workspaceWidgetTab: {
    padding: "8px 12px",
    borderRadius: 12,
    border: "1px solid #cbd5e1",
    background: "white",
    color: "#334155",
    cursor: "pointer",
    fontWeight: 700,
  },
  workspaceWidgetTabActive: {
    background: "#0f172a",
    color: "white",
    borderColor: "#0f172a",
  },
  workspaceWidgetClose: {
    padding: "8px 12px",
    borderRadius: 12,
    border: "1px solid #fecaca",
    background: "#fff1f2",
    color: "#be123c",
    cursor: "pointer",
    fontWeight: 700,
  },
  workspaceWidgetBody: {
    padding: 16,
    minHeight: 300,
    maxHeight: "calc(100vh - 220px)",
    overflow: "hidden",
  },
  assistantMessages: {
    display: "grid",
    gap: 10,
    maxHeight: 340,
    overflowY: "auto",
    paddingRight: 4,
  },
  assistantMessage: {
    borderRadius: 14,
    padding: "12px 14px",
    border: "1px solid #e2e8f0",
  },
  assistantMessageBot: {
    background: "#eff6ff",
    borderColor: "#bfdbfe",
  },
  assistantMessageUser: {
    background: "#f8fafc",
    borderColor: "#cbd5e1",
  },
  assistantComposer: {
    display: "grid",
    gap: 10,
  },
  assistantHint: {
    fontSize: 13,
    lineHeight: 1.5,
    color: "#475569",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: 14,
    padding: 12,
  },
  statusGreen: { background: "#dcfce7", color: "#166534" },
  statusYellow: { background: "#fef3c7", color: "#92400e" },
  statusRed: { background: "#fee2e2", color: "#991b1b" },
  statusBlue: { background: "#dbeafe", color: "#1d4ed8" },
  // Contraste de administracion: NEGRO = oscuro con texto claro; BLANCO = claro con borde.
  adminBlack: { background: "#1f2937", color: "#f9fafb", fontWeight: 700 },
  adminWhite: { background: "#f8fafc", color: "#0f172a", border: "1px solid #cbd5e1", fontWeight: 700 },
  // Semantica de direccion de la plata (NO es color de empresa): SALE plata = rojo; ENTRA = oscuro normal.
  amountOut: { color: "#dc2626" },
  amountIn: { color: "#0f172a" },
  statusGray: { background: "#e2e8f0", color: "#334155" },
  rowGreen: { background: "#dcfce7" },
  financialBrown: { background: "#92400e", color: "white" },
  financialBlack: { background: "#111827", color: "white" },
  financialRed: { background: "#b91c1c", color: "white" },
  financialDone: { background: "#166534", color: "white" },
  monthToolbar: { display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" },
  calendarMonthLabel: { fontSize: 16, fontWeight: 700, minWidth: 180, textTransform: "capitalize" },
  calendarLegend: { display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 12 },
  calendarWeekdays: { display: "grid", gridTemplateColumns: "repeat(7, minmax(0, 1fr))", gap: 8, marginBottom: 8 },
  calendarWeekdayCell: {
    textAlign: "center",
    fontSize: 12,
    fontWeight: 700,
    color: "#475569",
    padding: "8px 0",
    background: "#e2e8f0",
    borderRadius: 10,
  },
  calendarGrid: { display: "grid", gridTemplateColumns: "repeat(7, minmax(0, 1fr))", gap: 8 },
  yearCalendarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 12,
  },
  yearCalendarCard: {
    background: "#fff",
    border: "1px solid #cbd5e1",
    borderRadius: 14,
    padding: 12,
    display: "grid",
    gap: 8,
    alignContent: "start",
    minHeight: 180,
  },
  yearCalendarTitle: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: "capitalize",
    color: "#0f172a",
  },
  yearCalendarEvent: {
    borderRadius: 10,
    padding: 8,
  },
  yearCalendarEventTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#0f172a",
  },
  calendarCell: {
    minHeight: 170,
    background: "#fff",
    border: "1px solid #cbd5e1",
    borderRadius: 14,
    padding: 8,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  calendarCellMuted: { opacity: 0.45, background: "#f8fafc" },
  calendarCellHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8 },
  calendarEmpty: { fontSize: 12, color: "#64748b" },
  calendarItem: {
    border: "none",
    borderRadius: 10,
    padding: 8,
    textAlign: "left",
    cursor: "pointer",
    fontSize: 12,
  },
  calendarItemMeta: { fontSize: 11, opacity: 0.9, marginTop: 4 },
  ganttTrack: {
    width: "100%",
    height: 12,
    background: "#e2e8f0",
    borderRadius: 999,
    overflow: "hidden",
  },
  ganttFill: {
    height: "100%",
    borderRadius: 999,
    minWidth: 4,
  },
  timelineBlock: {
    display: "grid",
    gap: 6,
    minWidth: 180,
  },
  timelineLabel: {
    fontSize: 12,
    color: "#475569",
    textTransform: "capitalize",
  },
  fabricationGanttWrap: {
    display: "grid",
    gap: 12,
  },
  fabricationGanttHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  fabricationGanttMeta: {
    fontSize: 13,
    color: "#475569",
  },
  fabricationGanttLegend: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
  },
  fabricationGanttLegendItem: {
    fontSize: 12,
    color: "#64748b",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: 999,
    padding: "6px 10px",
  },
  fabricationGanttGrid: {
    display: "grid",
    gap: 10,
    overflowX: "auto",
  },
  fabricationGanttDays: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(52px, 1fr))",
    gap: 4,
    minWidth: 760,
  },
  fabricationGanttDay: {
    textAlign: "center",
    fontSize: 11,
    fontWeight: 700,
    color: "#334155",
    padding: "6px 4px",
    borderRadius: 8,
    background: "#eff6ff",
    border: "1px solid #dbeafe",
  },
  fabricationGanttDayWeekend: {
    background: "#f8fafc",
    borderColor: "#e2e8f0",
    color: "#64748b",
  },
  fabricationGanttRow: {
    display: "grid",
    gap: 8,
    minWidth: 760,
  },
  fabricationGanttJobMeta: {
    display: "grid",
    gap: 4,
  },
  fabricationGanttTrack: {
    position: "relative",
    height: 36,
    borderRadius: 12,
    background:
      "repeating-linear-gradient(90deg, #f8fafc 0px, #f8fafc 48px, #e2e8f0 48px, #e2e8f0 52px)",
    border: "1px solid #e2e8f0",
    overflow: "hidden",
  },
  fabricationGanttBar: {
    position: "absolute",
    top: 5,
    bottom: 5,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    padding: "0 10px",
    color: "#ffffff",
    fontSize: 12,
    fontWeight: 700,
    boxShadow: "0 10px 22px rgba(15, 23, 42, 0.18)",
    minWidth: 80,
  },
  fabricationGanttBarLabel: {
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  attendanceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(5, minmax(0, 1fr))",
    gap: 10,
    marginTop: 12,
  },
  attendanceCalendar: {
    display: "grid",
    gap: 10,
    marginTop: 12,
    width: "100%",
  },
  attendanceToolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginTop: 4,
  },
  attendanceMonthTitle: {
    fontSize: 20,
    fontWeight: 900,
    letterSpacing: 0.4,
    color: "#0f172a",
  },
  attendanceWeekdayHeader: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
    gap: 8,
    marginTop: 12,
  },
  attendanceWeekdayCell: {
    textAlign: "center",
    fontSize: 12,
    fontWeight: 900,
    color: "#475569",
    background: "#eff6ff",
    border: "1px solid #dbeafe",
    borderRadius: 10,
    padding: "7px 4px",
  },
  attendanceWeek: {
    border: "1px solid #dbeafe",
    borderRadius: 16,
    padding: 10,
    background: "#f8fafc",
    display: "grid",
    gap: 10,
    alignContent: "start",
    minWidth: 0,
    overflowX: "auto",
  },
  attendanceWeekTitle: {
    fontSize: 13,
    fontWeight: 800,
    color: "#0f172a",
  },
  attendanceWeekGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(118px, 1fr))",
    gap: 8,
  },
  attendanceCard: {
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    padding: 10,
    background: "#fff",
    minWidth: 118,
  },
  attendanceEmptyCard: {
    minHeight: 132,
    minWidth: 118,
    border: "1px dashed #e2e8f0",
    borderRadius: 12,
    background: "rgba(248,250,252,0.65)",
  },
  attendanceDayTitle: {
    fontSize: 12,
    color: "#475569",
    marginBottom: 8,
    textTransform: "capitalize",
  },
  attendanceHoursGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 8,
    marginTop: 8,
  },
  configDocRow: { display: "grid", gridTemplateColumns: "1fr auto", gap: 8, marginBottom: 8 },
  semaphoreBanner: {
    display: "flex",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
    padding: 12,
    borderRadius: 12,
    border: "2px solid",
    marginBottom: 16,
  },
  subCard: {
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  printSheet: {
    background: "white",
    color: "#0f172a",
    maxWidth: 960,
    margin: "0 auto",
    position: "relative",
  },
  printHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 20,
    alignItems: "flex-start",
    marginBottom: 20,
    breakInside: "avoid",
    pageBreakInside: "avoid",
  },
  printWatermark: {
    position: "fixed",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 160,
    fontWeight: 800,
    opacity: 0.06,
    pointerEvents: "none",
    zIndex: 0,
  },
  printWatermarkLogo: {
    maxWidth: "82%",
    maxHeight: "82%",
    objectFit: "contain",
    opacity: 1,
  },
  printLogoRow: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
  },
  printHeaderLogo: {
    width: 70,
    height: 70,
    objectFit: "contain",
    borderRadius: 10,
    border: "1px solid #e2e8f0",
    background: "white",
    padding: 6,
  },
  printBlock: {
    position: "relative",
    zIndex: 1,
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    padding: 14,
    marginBottom: 14,
    background: "rgba(255,255,255,0.96)",
    breakInside: "avoid",
    pageBreakInside: "avoid",
  },
  printReferenceImage: {
    width: "100%",
    height: 170,
    objectFit: "contain",
    background: "#f8fafc",
    border: "0.5px solid #e6e9ee",
    borderRadius: 8,
    breakInside: "avoid",
    pageBreakInside: "avoid",
  },
  printReferenceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))",
    gap: 10,
  },
  printSectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "flex-start",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  printSectionMeta: {
    display: "grid",
    gap: 4,
    minWidth: 180,
  },
  printTotals: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gap: 8,
    marginTop: 20,
    padding: 16,
    borderRadius: 12,
    border: "1px solid #cbd5e1",
    background: "rgba(255,255,255,0.96)",
    breakInside: "avoid",
    pageBreakInside: "avoid",
  },
};
